name: Dev Backend Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    # This tells the runner to execute all commands inside the backend folder
    defaults:
      run:
        working-directory: ./backend 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Virtual Env and Install Deps
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Restart with PM2
        run: |
          pm2 delete Apti-BE || true
          pm2 start venv/bin/uvicorn --name "Apti-BE" -- app.main:app --host 0.0.0.0 --port 8001