name: Dev Frontend Deploy

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'backend/**' # Trigger on EVERYTHING EXCEPT the backend folder

jobs:
  deploy-frontend:
    runs-on: self-hosted
    # No "defaults" section needed because we are in the root

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build # This creates the 'dist' folder in root

      - name: Serve with Python & PM2
        run: |
          pm2 delete Apti-FE || true
          # Serve from the 'dist' folder created in the root
          pm2 start "python3 -m http.server 3001 --directory dist" --name "Apti-FE"